In [1]:
import tensorflow as tf
import numpy as np
tf.compat.v1.enable_eager_execution()

In [11]:
cdf=tf.convert_to_tensor(np.array([0,0.1,0.2,0.5,0.8,0.9,1.0]),dtype=tf.float32)
u=tf.random.uniform([7])
u

<tf.Tensor: id=101, shape=(7,), dtype=float32, numpy=
array([0.18546939, 0.9113207 , 0.11926949, 0.35529637, 0.42297232,
       0.7419131 , 0.9935498 ], dtype=float32)>

In [12]:
inds = tf.searchsorted(cdf, u, side='right')
inds

<tf.Tensor: id=120, shape=(7,), dtype=int32, numpy=array([2, 6, 2, 3, 3, 4, 6])>

In [13]:
below = tf.maximum(0, inds-1)
below

<tf.Tensor: id=124, shape=(7,), dtype=int32, numpy=array([1, 5, 1, 2, 2, 3, 5])>

In [14]:
above = tf.minimum(cdf.shape[-1]-1, inds)
above

<tf.Tensor: id=126, shape=(7,), dtype=int32, numpy=array([2, 6, 2, 3, 3, 4, 6])>

In [15]:
inds_g = tf.stack([below, above], -1)
inds_g

<tf.Tensor: id=127, shape=(7, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [1, 2],
       [2, 3],
       [2, 3],
       [3, 4],
       [5, 6]])>

In [17]:
cdf_g = tf.gather(cdf, inds_g, axis=-1, batch_dims=len(inds_g.shape)-2)
cdf_g

<tf.Tensor: id=131, shape=(7, 2), dtype=float32, numpy=
array([[0.1, 0.2],
       [0.9, 1. ],
       [0.1, 0.2],
       [0.2, 0.5],
       [0.2, 0.5],
       [0.5, 0.8],
       [0.9, 1. ]], dtype=float32)>

In [19]:
bins=tf.linspace(0.0,1.0,7)
bins

<tf.Tensor: id=138, shape=(7,), dtype=float32, numpy=
array([0.        , 0.16666667, 0.33333334, 0.5       , 0.6666667 ,
       0.8333334 , 1.        ], dtype=float32)>

In [20]:
bins_g = tf.gather(bins, inds_g, axis=-1, batch_dims=len(inds_g.shape)-2)
bins_g

<tf.Tensor: id=140, shape=(7, 2), dtype=float32, numpy=
array([[0.16666667, 0.33333334],
       [0.8333334 , 1.        ],
       [0.16666667, 0.33333334],
       [0.33333334, 0.5       ],
       [0.33333334, 0.5       ],
       [0.5       , 0.6666667 ],
       [0.8333334 , 1.        ]], dtype=float32)>

In [21]:
denom = (cdf_g[..., 1]-cdf_g[..., 0])
denom

<tf.Tensor: id=149, shape=(7,), dtype=float32, numpy=
array([0.1       , 0.10000002, 0.1       , 0.3       , 0.3       ,
       0.3       , 0.10000002], dtype=float32)>

In [22]:
denom = tf.where(denom < 1e-5, tf.ones_like(denom), denom)
denom

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


<tf.Tensor: id=155, shape=(7,), dtype=float32, numpy=
array([0.1       , 0.10000002, 0.1       , 0.3       , 0.3       ,
       0.3       , 0.10000002], dtype=float32)>

In [23]:
t = (u-cdf_g[..., 0])/denom
t

<tf.Tensor: id=161, shape=(7,), dtype=float32, numpy=
array([0.8546939 , 0.11320707, 0.19269489, 0.51765454, 0.7432411 ,
       0.80637693, 0.93549824], dtype=float32)>

In [24]:
samples = bins_g[..., 0] + t * (bins_g[..., 1]-bins_g[..., 0])
samples

<tf.Tensor: id=176, shape=(7,), dtype=float32, numpy=
array([0.30911565, 0.8522012 , 0.19878249, 0.4196091 , 0.45720685,
       0.6343962 , 0.9892497 ], dtype=float32)>

New

In [24]:
import tensorflow as tf
a=tf.linspace(0.,1.,10)
a=tf.stack([a,a],0)
tf.where(a<0.5,tf.zeros_like(a),a)



<tf.Tensor: id=155, shape=(2, 10), dtype=float32, numpy=
array([[0.       , 0.       , 0.       , 0.       , 0.       , 0.5555556,
        0.6666667, 0.7777778, 0.8888889, 1.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.5555556,
        0.6666667, 0.7777778, 0.8888889, 1.       ]], dtype=float32)>